[package]
name = "lz4"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lz4_flex = { version = "0.11.0" }
wasm-bindgen = "0.2.83"
talc = { version = "3.1.0", default-features = false, features = ["lock_api"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
